"""Añadir campo time_used a ExamResult

Revision ID: 39b22fe9384d
Revises: d703753e61a2
Create Date: 2026-03-15 09:18:38.478218

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "39b22fe9384d"
down_revision = "d703753e61a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exam_results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("time_used", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exam_results", schema=None) as batch_op:
        batch_op.drop_column("time_used")

    # ### end Alembic commands ###
