"""empty message

Revision ID: 407f23d1d296
Revises: 7e1f47ee57a3
Create Date: 2025-09-17 16:01:00.733602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407f23d1d296'
down_revision = '7e1f47ee57a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_sessions')
    # ### end Alembic commands ###
