"""Add presented_questions to ActiveSession

Revision ID: 61ee79d080f7
Revises: 58897efec252
Create Date: 2025-12-08 09:02:31.485651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ee79d080f7'
down_revision = '58897efec252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presented_questions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_column('presented_questions')

    # ### end Alembic commands ###
