"""Update User model with codigo, nombre_completo, grado, and remove email

Revision ID: 7e1f47ee57a3
Revises: 
Create Date: 2025-09-13 22:54:07.709506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1f47ee57a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('grado', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_users_codigo', ['codigo'])
        # batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint('uq_users_codigo', type_='unique')
        batch_op.drop_column('grado')
        batch_op.drop_column('nombre_completo')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
