"""Add attempt_number to ExamResult

Revision ID: 805606c99ece
Revises: 61ee79d080f7
Create Date: 2026-01-31 10:45:55.064512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805606c99ece'
down_revision = '61ee79d080f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_results', schema=None) as batch_op:
        batch_op.drop_column('attempt_number')

    # ### end Alembic commands ###
